name: Setup Flixel
description: Setup Flixel
branding:
  icon: 'package'
  color: 'blue'
inputs:
  haxe-version:
    description: 'Version of Haxe to install via lix'
    required: false
  lime-version:
    description: 'Version of Lime to use'
    required: false
  openfl-version:
    description: 'Version of Openfl to use'
    required: false
  flixel-versions: 
    description: 'Version of Flixel libs to use'
    required: true
  test-location: 
    description: 'The location of the unit tests'
    required: false
  target:
    description: 'Which target to use'
    required: true
  run-tests:
    description: 'Whether to run flixel tests'
    required: false
    default: "false"
runs:
  using: 'node20'
  main: 'build/index.js'
