import haxe.macro.Compiler;
import sys.io.File;

function main()
{
	trace("Running: ncc build build/haxe-output.js -o build");
	Sys.command("ncc build build/haxe-output.js -o build");
	
	final path = "build/index.js";
	final file = File.getContent(path);
	if (file == null)
	{
		trace('No file named index.js found, creation unsuccesful');
	}
	else if (file.indexOf('// Generated by Haxe') == 0)
	{
		trace('File index.js was not updated');
	}
	else
	{
		trace('index.js created or updated, successfully');
		final haxe = Compiler.getDefine("haxe");
		File.saveContent(path, '// Generated by Haxe $haxe\n' + file);
	}
}
