import haxe.macro.Compiler;
import sys.io.File;

class Build {
	static function main() {
		Sys.command("ncc build build/haxe-output.js -o build");

		var path = "build/index.js";
		var file = File.getContent(path);
		var haxe = Compiler.getDefine("haxe");
		File.saveContent(path, '// Generated by Haxe $haxe\n' + file);
	}
}
