import haxe.macro.Compiler;
import sys.io.File;

function main() {
	Sys.command("ncc build build/haxe-output.js -o build");

	final path = "build/index.js";
	final file = File.getContent(path);
	if (file.indexOf('// Generated by Haxe') != 0) {
		final haxe = Compiler.getDefine("haxe");
		File.saveContent(path, '// Generated by Haxe $haxe\n' + file);
	}
}
